# Generated by Django 4.1.1 on 2022-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('tariff', models.IntegerField()),
                ('previous_units', models.IntegerField()),
                ('current_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Employee_ID', models.CharField(max_length=15)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('quarter_no', models.CharField(max_length=6)),
                ('meter_no', models.IntegerField()),
            ],
        ),
    ]
