# Generated by Django 4.1.1 on 2022-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitaranApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='net_billed_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='payable_amount',
            field=models.IntegerField(default=0),
        ),
    ]
