# Generated by Django 4.0.5 on 2022-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitaranApp', '0003_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Employee_ID',
            field=models.CharField(max_length=15),
        ),
    ]
