# Generated by Django 4.0.5 on 2022-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitaranApp', '0004_alter_bill_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='net_billed_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tariff',
        ),
        migrations.AddField(
            model_name='bill',
            name='KVA_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='Name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='meter_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='net_billed_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='quarter_no',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='rateP1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='rateP2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='rateP3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='sanction_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='unitP1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='unitP2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
