# Generated by Django 4.0.5 on 2022-10-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitaranApp', '0005_remove_bill_net_billed_amount_remove_bill_tariff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='quarter_no',
            field=models.CharField(max_length=15),
        ),
    ]
