# Generated by Django 4.0.5 on 2022-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VitaranApp', '0007_alter_bill_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rateP4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='rateP5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='rateP6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='unitP3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='unitP4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='unitP5',
            field=models.IntegerField(default=0),
        ),
    ]
